Fix archive tests on Windows
First problem:
The package failed to build:
```
 # gitlab.com/gitlab-org/gitlab-runner/helpers/archives [gitlab.com/gitlab-org/gitlab-runner/helpers/archives.test]
helpers\archives\zip_create_test.go:37:9: undefined: syscall.Mkfifo
FAIL	gitlab.com/gitlab-org/gitlab-runner/helpers/archives [build failed]
```

Second problem:
The current Go version that we use (1.13.8) does not support file
permission bits. This was added in Go 1.14.0 with
https://github.com/golang/go/commit/16f0f9c8e1e767d10d483939981e3b2242554c33.
However it doesn't support everything which is why we changed
permissions to `0444`. We have to finish our Go upgrade in
https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1884

Thrid problem:
On windows the Extra bits are different because [we don't add UIDgid
fields](https://gitlab.com/gitlab-org/gitlab-runner/-/blob/67a9ab49587810858e578b320cfdac8ae98198e7/helpers/archives/zip_extra_windows.go)

closes https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26451